"""Shared GLSL and C codegen for constant-folded SHA-256 block compressors (scalar / uvec2 / uvec4)."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from typing import List

MASK32 = 0xFFFFFFFF


class SlotKind(Enum):
    CONST = auto()
    VAR = auto()


@dataclass(frozen=True)
class WidthConfig:
    width: int
    glsl_type: str
    round_macro: str
    broadcast_fn: str
    fn_suffix: str
    file_suffix: str
    miner_comp: str


WIDTH_SCALAR = WidthConfig(
    width=1,
    glsl_type="uint",
    round_macro="SHA256_ROUND",
    broadcast_fn="",
    fn_suffix="",
    file_suffix="scalar",
    miner_comp="miner.comp",
)
WIDTH_UVEC2 = WidthConfig(
    width=2,
    glsl_type="uvec2",
    round_macro="SHA256_ROUND_2WAY",
    broadcast_fn="broadcast_uvec2",
    fn_suffix="_2way",
    file_suffix="uvec2",
    miner_comp="miner_uvec2.comp",
)
WIDTH_UVEC4 = WidthConfig(
    width=4,
    glsl_type="uvec4",
    round_macro="SHA256_ROUND_4WAY",
    broadcast_fn="broadcast_uvec4",
    fn_suffix="_4way",
    file_suffix="uvec4",
    miner_comp="miner_uvec4.comp",
)
ALL_WIDTHS = (WIDTH_SCALAR, WIDTH_UVEC2, WIDTH_UVEC4)


def sig0_int(x: int) -> int:
    x &= MASK32
    return (((x >> 7) | (x << 25)) ^ ((x >> 18) | (x << 14)) ^ (x >> 3)) & MASK32


def sig1_int(x: int) -> int:
    x &= MASK32
    return (((x >> 17) | (x << 15)) ^ ((x >> 19) | (x << 13)) ^ (x >> 10)) & MASK32


class WSlot:
    __slots__ = ("kind", "value")

    def __init__(self, kind: SlotKind, value: int = 0) -> None:
        self.kind = kind
        self.value = value & MASK32

    @staticmethod
    def const(v: int) -> "WSlot":
        return WSlot(SlotKind.CONST, v)

    @staticmethod
    def var() -> "WSlot":
        return WSlot(SlotKind.VAR, 0)

    def eval(self, w_int: List[int], idx: int) -> int:
        if self.kind == SlotKind.CONST:
            return self.value
        return w_int[idx] & MASK32


def glsl_const(v: int, cfg: WidthConfig) -> str:
    lit = f"0x{v & MASK32:08x}u"
    if cfg.width == 1:
        return lit
    return f"{cfg.broadcast_fn}({lit})"


def glsl_zero(cfg: WidthConfig) -> str:
    if cfg.width == 1:
        return "0u"
    return f"{cfg.glsl_type}(0u)"


def term_glsl(slot: WSlot, idx: int, cfg: WidthConfig) -> str:
    if slot.kind == SlotKind.CONST:
        return glsl_const(slot.value, cfg)
    return f"w[{idx}]"


def sig0_glsl(slot: WSlot, idx: int, cfg: WidthConfig) -> str:
    if slot.kind == SlotKind.CONST:
        return glsl_const(sig0_int(slot.value), cfg)
    return f"SIG0(w[{idx}])"


def sig1_glsl(slot: WSlot, idx: int, cfg: WidthConfig) -> str:
    if slot.kind == SlotKind.CONST:
        return glsl_const(sig1_int(slot.value), cfg)
    return f"SIG1(w[{idx}])"


def emit_compress_body(slots: List[WSlot], cfg: WidthConfig) -> List[str]:
    lines: List[str] = []
    working = list(slots)
    for i in range(64):
        if i < 16:
            lines.append(
                f"    {cfg.round_macro}(a, b, c, d, e, f, g, h, w[{i}], K[{i}]);"
            )
        else:
            idx = i & 15
            i16, i15, i7, i2 = (i - 16) & 15, (i - 15) & 15, (i - 7) & 15, (i - 2) & 15
            s16, s15, s7, s2 = working[i16], working[i15], working[i7], working[i2]
            update = (
                f"w[{idx}] = {term_glsl(s16, i16, cfg)} + {sig0_glsl(s15, i15, cfg)} + "
                f"{term_glsl(s7, i7, cfg)} + {sig1_glsl(s2, i2, cfg)};"
            )
            lines.append(f"    {update}")
            lines.append(
                f"    {cfg.round_macro}(a, b, c, d, e, f, g, h, w[{idx}], K[{i}]);"
            )
            working[idx] = WSlot.var()
    return lines


def header_comment(generator: str, description: str, cfg: WidthConfig) -> str:
    if cfg.width == 1:
        requires = f"{cfg.round_macro}, SIG0, SIG1, and K[] from {cfg.miner_comp}."
    else:
        requires = (
            f"{cfg.round_macro}, SIG0, SIG1, K[], and {cfg.broadcast_fn} from {cfg.miner_comp}."
        )
    return (
        f"// Auto-generated by tools/{generator} — do not edit.\n"
        f"// {description}\n"
        f"// Requires {requires}"
    )


def c_const(v: int) -> str:
    return f"0x{v & MASK32:08x}u"


def c_zero() -> str:
    return "0u"


def term_c(slot: WSlot, idx: int) -> str:
    if slot.kind == SlotKind.CONST:
        return c_const(slot.value)
    return f"w[{idx}]"


def sig0_c(slot: WSlot, idx: int) -> str:
    if slot.kind == SlotKind.CONST:
        return c_const(sig0_int(slot.value))
    return f"SIG0(w[{idx}])"


def sig1_c(slot: WSlot, idx: int) -> str:
    if slot.kind == SlotKind.CONST:
        return c_const(sig1_int(slot.value))
    return f"SIG1(w[{idx}])"


def emit_compress_body_c(slots: List[WSlot]) -> List[str]:
    lines: List[str] = []
    working = list(slots)
    for i in range(64):
        if i < 16:
            lines.append(f"    SHA256_ROUND(a, b, c, d, e, f, g, h, w[{i}], K[{i}]);")
        else:
            idx = i & 15
            i16, i15, i7, i2 = (i - 16) & 15, (i - 15) & 15, (i - 7) & 15, (i - 2) & 15
            s16, s15, s7, s2 = working[i16], working[i15], working[i7], working[i2]
            update = (
                f"w[{idx}] = {term_c(s16, i16)} + {sig0_c(s15, i15)} + "
                f"{term_c(s7, i7)} + {sig1_c(s2, i2)};"
            )
            lines.append(f"    {update}")
            lines.append(f"    SHA256_ROUND(a, b, c, d, e, f, g, h, w[{idx}], K[{i}]);")
            working[idx] = WSlot.var()
    return lines


def header_comment_c(generator: str, description: str) -> str:
    return (
        f"// Auto-generated by tools/{generator} — do not edit.\n"
        f"// {description}\n"
        f"// Requires SHA256_ROUND, SIG0, SIG1, and K[] from sha256_btc_fast.c."
    )
