/*
 * Runtime Digital Rain configuration (persisted). Defaults mirror [DigitalRainConstants].
 */

package com.btcminer.android.ui.digitalrain

/** Persisted tunables for [DigitalRainView]; defaults equal shipped [DigitalRainConstants]. */
data class DigitalRainSettings(
    val animMode: DigitalRainAnimMode,
    val glyphAtlasMode: DigitalRainGlyphAtlasMode,
    val defaultLineWidth: Int,
    val defaultLetterHeight: Int,
    val fontScale: Int,
    val useBigText: Boolean,
    val columnStartYMultiplier: Int,
    val lineLenMin: Int,
    val lineLenMax: Int,
    val lineSpeedMin: Int,
    val lineSpeedMax: Int,
    val matrixFrameMs: Long,
    val headCharR: Int,
    val headCharG: Int,
    val headCharB: Int,
    val rainTextR: Int,
    val rainTextG: Int,
    val rainTextB: Int,
    val rainBackgroundR: Int,
    val rainBackgroundG: Int,
    val rainBackgroundB: Int,
    val asciiRange1Start: Int,
    val asciiRange1End: Int,
    val asciiRange2Start: Int,
    val asciiRange2End: Int,
    val alphabetOnly: Boolean,
    val keyResetTimeMs: Long,
    val keyLengthColumns: Int,
    val enableKeyMode: Boolean,
    val stickyKeyHighlight: Boolean,
    val bitcoinOrangeKeyHighlight: Boolean,
    val depthEnabled: Boolean,
    val depthStreakCount: Int,
    val depthMaxScalePercent: Int,
    val textFrameMs: Long,
    val showcaseMessage: String,
) {
    companion object {
        fun defaults(): DigitalRainSettings = DigitalRainSettings(
            animMode = DigitalRainConstants.ANIM_MODE,
            glyphAtlasMode = DigitalRainConstants.GLYPH_ATLAS_MODE,
            defaultLineWidth = DigitalRainConstants.DEFAULT_LINE_WIDTH,
            defaultLetterHeight = DigitalRainConstants.DEFAULT_LETTER_HEIGHT,
            fontScale = DigitalRainConstants.FONT_SCALE,
            useBigText = DigitalRainConstants.USE_BIG_TEXT,
            columnStartYMultiplier = DigitalRainConstants.COLUMN_START_Y_MULTIPLIER,
            lineLenMin = DigitalRainConstants.LINE_LEN_MIN,
            lineLenMax = DigitalRainConstants.LINE_LEN_MAX,
            lineSpeedMin = DigitalRainConstants.LINE_SPEED_MIN,
            lineSpeedMax = DigitalRainConstants.LINE_SPEED_MAX,
            matrixFrameMs = DigitalRainConstants.MATRIX_FRAME_MS,
            headCharR = DigitalRainConstants.HEAD_CHAR_R,
            headCharG = DigitalRainConstants.HEAD_CHAR_G,
            headCharB = DigitalRainConstants.HEAD_CHAR_B,
            rainTextR = DigitalRainConstants.RAIN_TEXT_R,
            rainTextG = DigitalRainConstants.RAIN_TEXT_G,
            rainTextB = DigitalRainConstants.RAIN_TEXT_B,
            rainBackgroundR = DigitalRainConstants.RAIN_BACKGROUND_R,
            rainBackgroundG = DigitalRainConstants.RAIN_BACKGROUND_G,
            rainBackgroundB = DigitalRainConstants.RAIN_BACKGROUND_B,
            asciiRange1Start = DigitalRainConstants.ASCII_RANGE_1_START,
            asciiRange1End = DigitalRainConstants.ASCII_RANGE_1_END,
            asciiRange2Start = DigitalRainConstants.ASCII_RANGE_2_START,
            asciiRange2End = DigitalRainConstants.ASCII_RANGE_2_END,
            alphabetOnly = DigitalRainConstants.ALPHABET_ONLY,
            keyResetTimeMs = DigitalRainConstants.KEY_RESET_TIME_MS,
            keyLengthColumns = DigitalRainConstants.KEY_LENGTH_COLUMNS,
            enableKeyMode = DigitalRainConstants.ENABLE_KEY_MODE,
            stickyKeyHighlight = DigitalRainConstants.STICKY_KEY_HIGHLIGHT,
            bitcoinOrangeKeyHighlight = false,
            depthEnabled = DigitalRainConstants.DEPTH_ENABLED,
            depthStreakCount = DigitalRainConstants.DEPTH_STREAK_COUNT,
            depthMaxScalePercent = DigitalRainConstants.DEPTH_MAX_SCALE_PERCENT,
            textFrameMs = DigitalRainConstants.TEXT_FRAME_MS,
            showcaseMessage = DigitalRainConstants.SHOWCASE_MESSAGE,
        )
    }
}
