# Reads SPV_FILE (SPIR-V binary) and writes OUT_FILE (C header with byte array).
file(READ "${SPV_FILE}" SPV_DATA HEX)
string(LENGTH "${SPV_DATA}" SPV_HEX_LEN)
math(EXPR SPV_BYTE_LEN "${SPV_HEX_LEN} / 2")

set(LINE "    ")
set(COL 0)
set(OUT_LINES "")
foreach(C RANGE 0 ${SPV_HEX_LEN} 2)
    if(C LESS SPV_HEX_LEN)
        string(SUBSTRING "${SPV_DATA}" ${C} 2 BYTE_HEX)
        set(LINE "${LINE}0x${BYTE_HEX}, ")
        math(EXPR COL "${COL} + 1")
        if(COL GREATER_EQUAL 12)
            set(OUT_LINES "${OUT_LINES}${LINE}\n")
            set(LINE "    ")
            set(COL 0)
        endif()
    endif()
endforeach()
if(LINE)
    string(REGEX REPLACE ", $" "" LINE "${LINE}")
    set(OUT_LINES "${OUT_LINES}${LINE}\n")
endif()

set(CONTENT "/* Auto-generated from miner.spv - do not edit */\n#ifndef MINER_SPV_H\n#define MINER_SPV_H\nstatic const unsigned char g_miner_spv[] = {\n${OUT_LINES}};\nstatic const unsigned int g_miner_spv_len = ${SPV_BYTE_LEN};\n#endif\n")
file(WRITE "${OUT_FILE}" "${CONTENT}")
